apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    zone: pod
    version: v1
spec:
  containers:
  - name: mme
    image: stahu/atsirepo:firstone
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: dockerrepo